# Generated by Django 2.2 on 2020-08-22 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='beditor',
            name='maps',
            field=models.ImageField(blank=True, null=True, upload_to='images/maps/%Y/%m/%d'),
        ),
    ]
