# Generated by Django 2.2 on 2020-08-22 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='maps',
            field=models.ImageField(blank=True, null=True, upload_to='images/maps/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='like',
            name='image_five',
            field=models.ImageField(blank=True, null=True, upload_to='images/recommend/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='like',
            name='image_four',
            field=models.ImageField(blank=True, null=True, upload_to='images/recommend/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='like',
            name='image_one',
            field=models.ImageField(blank=True, null=True, upload_to='images/recommend/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='like',
            name='image_three',
            field=models.ImageField(blank=True, null=True, upload_to='images/recommend/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='like',
            name='image_two',
            field=models.ImageField(blank=True, null=True, upload_to='images/recommend/%Y/%m/%d'),
        ),
    ]
