# Generated by Django 2.2 on 2020-08-22 06:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('text', models.TextField(blank=True)),
                ('division', models.CharField(max_length=100)),
                ('rating', models.CharField(blank=True, max_length=10, null=True)),
                ('address', models.CharField(max_length=200)),
                ('call', models.CharField(max_length=100)),
                ('park', models.CharField(max_length=50)),
                ('hours', models.CharField(max_length=50)),
                ('price', models.TextField(max_length=200)),
                ('image_one', models.ImageField(blank=True, null=True, upload_to='images/like/%Y/%m/%d')),
                ('image_two', models.ImageField(blank=True, null=True, upload_to='images/like/%Y/%m/%d')),
                ('image_three', models.ImageField(blank=True, null=True, upload_to='images/like/%Y/%m/%d')),
                ('image_four', models.ImageField(blank=True, null=True, upload_to='images/like/%Y/%m/%d')),
                ('image_five', models.ImageField(blank=True, null=True, upload_to='images/like/%Y/%m/%d')),
                ('maps', models.ImageField(blank=True, null=True, upload_to='images/maps/%Y/%m/%d')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
                ('favorite', models.ManyToManyField(blank=True, related_name='favorite_post', to=settings.AUTH_USER_MODEL)),
                ('like', models.ManyToManyField(blank=True, related_name='like_post', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
