# Generated by Django 2.2 on 2020-08-22 05:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('division', models.CharField(max_length=100)),
                ('rating', models.CharField(blank=True, max_length=10, null=True)),
                ('address', models.CharField(max_length=200)),
                ('call', models.CharField(max_length=100)),
                ('park', models.CharField(max_length=50)),
                ('hours', models.CharField(max_length=50)),
                ('price', models.TextField(max_length=200)),
                ('context', models.TextField(blank=True, max_length=500, null=True)),
                ('image_one', models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%d')),
                ('image_two', models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%d')),
                ('image_three', models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%d')),
                ('image_four', models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%d')),
                ('image_five', models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%d')),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('division', models.CharField(max_length=100)),
                ('rating', models.CharField(blank=True, max_length=10, null=True)),
                ('address', models.CharField(max_length=200)),
                ('call', models.CharField(max_length=100)),
                ('park', models.CharField(max_length=50)),
                ('hours', models.CharField(max_length=50)),
                ('price', models.TextField(max_length=200)),
                ('context', models.TextField(blank=True, max_length=500, null=True)),
                ('image_one', models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%d')),
                ('image_two', models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%d')),
                ('image_three', models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%d')),
                ('image_four', models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%d')),
                ('image_five', models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%d')),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Editor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('division', models.CharField(max_length=100)),
                ('rating', models.CharField(blank=True, max_length=10, null=True)),
                ('address', models.CharField(max_length=200)),
                ('call', models.CharField(max_length=100)),
                ('park', models.CharField(max_length=50)),
                ('hours', models.CharField(max_length=50)),
                ('price', models.TextField(max_length=200)),
                ('context', models.TextField(blank=True, max_length=500, null=True)),
                ('image_one', models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%d')),
                ('image_two', models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%d')),
                ('image_three', models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%d')),
                ('image_four', models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%d')),
                ('image_five', models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%d')),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('division', models.CharField(max_length=100)),
                ('rating', models.CharField(blank=True, max_length=10, null=True)),
                ('address', models.CharField(max_length=200)),
                ('call', models.CharField(max_length=100)),
                ('park', models.CharField(max_length=50)),
                ('hours', models.CharField(max_length=50)),
                ('price', models.TextField(max_length=200)),
                ('context', models.TextField(blank=True, max_length=500, null=True)),
                ('image_one', models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%d')),
                ('image_two', models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%d')),
                ('image_three', models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%d')),
                ('image_four', models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%d')),
                ('image_five', models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%d')),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
