# Generated by Django 2.2 on 2020-08-22 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='art',
            name='maps',
            field=models.ImageField(blank=True, null=True, upload_to='images/maps/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='escape',
            name='maps',
            field=models.ImageField(blank=True, null=True, upload_to='images/maps/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='food',
            name='maps',
            field=models.ImageField(blank=True, null=True, upload_to='images/maps/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='theater',
            name='maps',
            field=models.ImageField(blank=True, null=True, upload_to='images/maps/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='travle',
            name='maps',
            field=models.ImageField(blank=True, null=True, upload_to='images/maps/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='art',
            name='image_five',
            field=models.ImageField(blank=True, null=True, upload_to='images/tag/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='art',
            name='image_four',
            field=models.ImageField(blank=True, null=True, upload_to='images/tag/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='art',
            name='image_one',
            field=models.ImageField(blank=True, null=True, upload_to='images/tag/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='art',
            name='image_three',
            field=models.ImageField(blank=True, null=True, upload_to='images/tag/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='art',
            name='image_two',
            field=models.ImageField(blank=True, null=True, upload_to='images/tag/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='escape',
            name='image_five',
            field=models.ImageField(blank=True, null=True, upload_to='images/tag/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='escape',
            name='image_four',
            field=models.ImageField(blank=True, null=True, upload_to='images/tag/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='escape',
            name='image_one',
            field=models.ImageField(blank=True, null=True, upload_to='images/tag/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='escape',
            name='image_three',
            field=models.ImageField(blank=True, null=True, upload_to='images/tag/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='escape',
            name='image_two',
            field=models.ImageField(blank=True, null=True, upload_to='images/tag/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='food',
            name='image_five',
            field=models.ImageField(blank=True, null=True, upload_to='images/tag/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='food',
            name='image_four',
            field=models.ImageField(blank=True, null=True, upload_to='images/tag/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='food',
            name='image_one',
            field=models.ImageField(blank=True, null=True, upload_to='images/tag/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='food',
            name='image_three',
            field=models.ImageField(blank=True, null=True, upload_to='images/tag/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='food',
            name='image_two',
            field=models.ImageField(blank=True, null=True, upload_to='images/tag/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='theater',
            name='image_five',
            field=models.ImageField(blank=True, null=True, upload_to='images/tag/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='theater',
            name='image_four',
            field=models.ImageField(blank=True, null=True, upload_to='images/tag/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='theater',
            name='image_one',
            field=models.ImageField(blank=True, null=True, upload_to='images/tag/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='theater',
            name='image_three',
            field=models.ImageField(blank=True, null=True, upload_to='images/tag/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='theater',
            name='image_two',
            field=models.ImageField(blank=True, null=True, upload_to='images/tag/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='travle',
            name='image_five',
            field=models.ImageField(blank=True, null=True, upload_to='images/tag/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='travle',
            name='image_four',
            field=models.ImageField(blank=True, null=True, upload_to='images/tag/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='travle',
            name='image_one',
            field=models.ImageField(blank=True, null=True, upload_to='images/tag/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='travle',
            name='image_three',
            field=models.ImageField(blank=True, null=True, upload_to='images/tag/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='travle',
            name='image_two',
            field=models.ImageField(blank=True, null=True, upload_to='images/tag/%Y/%m/%d'),
        ),
    ]
