#URLconf file
from django.urls import path
from django.conf.urls import url
from django.conf.urls.static import static
from django.conf import settings
from . import views

urlpatterns = [
    #index page
    path('', views.index, name='index'),
    path('introduce/', views.introduce, name='introduce'),
    path('tag/', views.tag, name='tag'),
    # tag one
    path('tag1_1', views.tag1_1, name='tag1_1'),
    path('tag1_2', views.tag1_2, name='tag1_2'),
    path('tag1_3', views.tag1_3, name='tag1_3'),
    path('tag1_4', views.tag1_4, name='tag1_4'),
    path('tag1_5', views.tag1_5, name='tag1_5'),
    path('tag1_6', views.tag1_6, name='tag1_6'),
    # tag two
    path('tag2_1', views.tag2_1, name='tag2_1'),
    path('tag2_2', views.tag2_2, name='tag2_2'),
    path('tag2_3', views.tag2_3, name='tag2_3'),
    path('tag2_4', views.tag2_4, name='tag2_4'),
    path('tag2_5', views.tag2_5, name='tag2_5'),
    path('tag2_6', views.tag2_6, name='tag2_6'),
    # tag three
    path('tag3_1', views.tag3_1, name='tag3_1'),
    path('tag3_2', views.tag3_2, name='tag3_2'),
    path('tag3_3', views.tag3_3, name='tag3_3'),
    path('tag3_4', views.tag3_4, name='tag3_4'),
    path('tag3_5', views.tag3_5, name='tag3_5'),
    path('tag3_6', views.tag3_6, name='tag3_6'),
    # tag four
    path('tag4_1', views.tag4_1, name='tag4_1'),
    path('tag4_2', views.tag4_2, name='tag4_2'),
    path('tag4_3', views.tag4_3, name='tag4_3'),
    path('tag4_4', views.tag4_4, name='tag4_4'),
    path('tag4_5', views.tag4_5, name='tag4_5'),
    path('tag4_6', views.tag4_6, name='tag4_6'),
    # tag five
    path('tag5_1', views.tag5_1, name='tag5_1'),
    path('tag5_2', views.tag5_2, name='tag5_2'),
    path('tag5_3', views.tag5_3, name='tag5_3'),
    path('tag5_4', views.tag5_4, name='tag5_4'),
    path('tag5_5', views.tag5_5, name='tag5_5'),
    path('tag5_6', views.tag5_6, name='tag5_6'),
    # tag six
    path('tag6_1', views.tag6_1, name='tag6_1'),
    path('tag6_2', views.tag6_2, name='tag6_2'),
    path('tag6_3', views.tag6_3, name='tag6_3'),
    path('tag6_4', views.tag6_4, name='tag6_4'),
    path('tag6_5', views.tag6_5, name='tag6_5'),
    path('tag6_6', views.tag6_6, name='tag6_6'),
    # tag list
    path('tag_list1', views.tag_list1, name='tag_list1'),
    path('tag_list2', views.tag_list2, name='tag_list2'),
    path('tag_list3', views.tag_list3, name='tag_list3'),
    path('tag_list4', views.tag_list4, name='tag_list4'),
    path('tag_list5', views.tag_list5, name='tag_list5'),
    path('tag_list6', views.tag_list6, name='tag_list6'),
    # area one
    path('area1_1', views.area1_1, name='area1_1'),
    path('area1_2', views.area1_2, name='area1_2'),
    path('area1_3', views.area1_3, name='area1_3'),
    path('area1_4', views.area1_4, name='area1_4'),
    path('area1_5', views.area1_5, name='area1_5'),
    path('area1_6', views.area1_6, name='area1_6'),
    # tag two
    path('area2_1', views.area2_1, name='area2_1'),
    path('area2_2', views.area2_2, name='area2_2'),
    path('area2_3', views.area2_3, name='area2_3'),
    path('area2_4', views.area2_4, name='area2_4'),
    path('area2_5', views.area2_5, name='area2_5'),
    path('area2_6', views.area2_6, name='area2_6'),
    ## area three
    path('area3_1', views.area3_1, name='area3_1'),
    path('area3_2', views.area3_2, name='area3_2'),
    path('area3_3', views.area3_3, name='area3_3'),
    path('area3_4', views.area3_4, name='area3_4'),
    path('area3_5', views.area3_5, name='area3_5'),
    path('area3_6', views.area3_6, name='area3_6'),
    ## area four
    path('area4_1', views.area4_1, name='area4_1'),
    path('area4_2', views.area4_2, name='area4_2'),
    path('area4_3', views.area4_3, name='area4_3'),
    path('area4_4', views.area4_4, name='area4_4'),
    path('area4_5', views.area4_5, name='area4_5'),
    path('area4_6', views.area4_6, name='area4_6'),
    ## area five
    path('area5_1', views.area5_1, name='area5_1'),
    path('area5_2', views.area5_2, name='area5_2'),
    path('area5_3', views.area5_3, name='area5_3'),
    path('area5_4', views.area5_4, name='area5_4'),
    path('area5_5', views.area5_5, name='area5_5'),
    path('area5_6', views.area5_6, name='area5_6'),
    ## area six
    path('area6_1', views.area6_1, name='area6_1'),
    path('area6_2', views.area6_2, name='area6_2'),
    path('area6_3', views.area6_3, name='area6_3'),
    path('area6_4', views.area6_4, name='area6_4'),
    path('area6_5', views.area6_5, name='area6_5'),
    path('area6_6', views.area6_6, name='area6_6'),
    # area list
    path('area_list1', views.area_list1, name='area_list1'),
    path('area_list2', views.area_list2, name='area_list2'),
    path('area_list3', views.area_list3, name='area_list3'),
    path('area_list4', views.area_list4, name='area_list4'),
    path('area_list5', views.area_list5, name='area_list5'),
    path('area_list6', views.area_list6, name='area_list6'),
    # body list
    path('contact/', views.contact, name='contact'),
    path('recommendation1/', views.recommendation1, name='recommendation1'),
    path('recommendation2/', views.recommendation2, name='recommendation2'),
    path('recommendation3/', views.recommendation3, name='recommendation3'),
    path('recommendation4/', views.recommendation4, name='recommendation4'),
    path('index_editor1/', views.index_editor1, name='index_editor1'),
    path('index_editor2/', views.index_editor2, name='index_editor2'),
    path('index_editor3/', views.index_editor3, name='index_editor3'),
    # recommend one
    path('recommend1_1/', views.recommend1_1, name='recommend1_1'),
    path('recommend1_2/', views.recommend1_2, name='recommend1_2'),
    path('recommend1_3/', views.recommend1_3, name='recommend1_3'),
    path('recommend1_4/', views.recommend1_4, name='recommend1_4'),
    path('recommend1_5/', views.recommend1_5, name='recommend1_5'),
    path('recommend1_6/', views.recommend1_6, name='recommend1_6'),
    # recommend three
    path('recommend3_1/', views.recommend3_1, name='recommend3_1'),
    path('recommend3_2/', views.recommend3_2, name='recommend3_2'),
    path('recommend3_3/', views.recommend3_3, name='recommend3_3'),
    path('recommend3_4/', views.recommend3_4, name='recommend3_4'),
    path('recommend3_5/', views.recommend3_5, name='recommend3_5'),
    path('recommend3_6/', views.recommend3_6, name='recommend3_6'),
    # recommend four
    path('recommend4_1/', views.recommend4_1, name='recommend4_1'),
    path('recommend4_2/', views.recommend4_2, name='recommend4_2'),
    path('recommend4_3/', views.recommend4_3, name='recommend4_3'),
]